# Generated by Django 4.2.3 on 2023-07-18 16:54
from __future__ import annotations

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testmain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
