# Generated by Django 5.2.8 on 2025-11-17 18:12
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("testmain", "0002_payment_billing_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for confirmation"),
                    ("preauth", "Pre-authorized"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("error", "Error"),
                    ("input", "Input"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
